export const GET_BRANDS = 'GET_BRANDS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAILED = 'GET_BRANDS_FAILED';

export const GET_BRAND = 'GET_BRAND';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAILED = 'GET_BRAND_FAILED';

export const LOAD_MORE_BRANDS = 'LOAD_MORE_BRANDS';
export const LOAD_MORE_BRANDS_SUCCESS = 'LOAD_MORE_BRANDS_SUCCESS';
export const LOAD_MORE_BRANDS_FAILED = 'LOAD_MORE_BRANDS_FAILED';

export const RESET_STATE = 'RESET_STATE';
