const IMAGES = {
  cover: require('assets/images/splash.png'),
  //   icons
  iconBack: require('assets/images/icons/back.png'),
  iconFacebook: require('assets/images/icons/facebook.png'),
  iconTwitter: require('assets/images/icons/twitter.png'),
  iconGoogle: require('assets/images/icons/google.png'),
  iconMenu: require('assets/images/icons/menu.png'),
  iconMenuOpen: require('assets/images/icons/menuOpen.png'),
  iconCart: require('assets/images/icons/cart.png'),
  iconSearch: require('assets/images/icons/search.png'),
  iconVoice: require('assets/images/icons/voice.png'),
  iconHome: require('assets/images/icons/home.png'),
  iconHeart: require('assets/images/icons/heart.png'),
  iconHeartLiked: require('assets/images/icons/heartLiked.png'),
  iconBag: require('assets/images/icons/bag.png'),
  iconWallet: require('assets/images/icons/wallet.png'),
  iconSun: require('assets/images/icons/sun.png'),
  iconAvatar: require('assets/images/icons/avatar.png'),
  iconInfo: require('assets/images/icons/info.png'),
  iconLogout: require('assets/images/icons/logout.png'),
  iconBadge: require('assets/images/icons/badge.png'),
  iconBagDrawer: require('assets/images/icons/bagDrawer.png'),
  iconHeartDrawer: require('assets/images/icons/heartDrawer.png'),
  iconWalletDrawer: require('assets/images/icons/walletDrawer.png'),
  iconClock: require('assets/images/icons/clock.png'),
  reviewerAvatar: require('assets/images/icons/reviewer.png'),
  ratingStart: require('assets/images/icons/startRate.png'),
  // products
  product1: require('assets/images/products/l1.png'),
  product2: require('assets/images/products/l2.png'),
  product3: require('assets/images/products/l3.png'),
  product4: require('assets/images/products/l4.png'),
  productDetail1: require('assets/images/products/detailProduct1.png'),
  // Brands
  adidas: require('assets/images/brands/adidas.png'),
  nike: require('assets/images/brands/nike.png'),
  fila: require('assets/images/brands/fila.png'),
  puma: require('assets/images/brands/puma.png'),
};

export default IMAGES;
