export {default as GetStarted} from './GetStarted'
export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as Dummy} from './Dummy'
export {default as Menu} from './Menu'
