# Auth

# @name login
POST http://localhost:8080/api/auth/login

###

# @name listAllProducts
POST http://localhost:3000/api/products
Content-Type: application/application/json
{
    
}

###

# @name pagination
GET http://localhost:3000/api/products?_page=1&_limit=20